### ISSUE TITLE
How do you unsubscribe?

### ISSUE THREAD

**Issue by rusenask** [lileio/pubsub#20]
Can't see in the handler/subscriber or is it only possible to unsubscribe with the Shutdown() ?

**Comment by arbarlow** [comment]
Hey @rusenask, I don't think this is implemented yet! I'd welcome a PR

**Comment by arbarlow** [comment]
Do you still need this?

**Comment by rusenask** [comment]
I think I avoided using unsubscribe on that project. Lately I have been using this https://gocloud.dev/ package to wrap around different message brokers :)

**Comment by arbarlow** [comment]
Ah yes ok, it's quite nice yes. lile/pubsub providers serialisation on top and hopefully some code gen too soon!

**Comment by rusenask** [comment]
nice :) Yeah, tbh it's always just protobuf marshal/unmarshall around the messaging parts so it would be nice to save some time!
